baseurl = "http://hoverfly.io/"
languageCode = "en-us"
title = "Hoverfly"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "SpectoLabs"
	description = "Open Source API Simulation"
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/SpectoLabs/hoverfly"

	version = "0.9.0"
	logo = "img/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "black"
    	accent  = "orange"

    [params.font]
    	text = "Lato"
    	code = "Consolas"


[social]
	twitter = "spectolabs"
	github  = "SpectoLabs"
	email   = "contact@specto.io"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Introduction"
	url    = "introduction/"
	weight = 10

[[menu.main]]
	name   = "Usage"
	url    = "usage/"
	weight = 30

[[menu.main]]
	name   = "Reference"
	url    = "reference/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
